// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Returns the signed-in user's Financeit profile (email, full name, role).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("id, email, full_name, role, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-clients.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_clients_default = defineTool2({
  name: "list_my_clients",
  title: "List my clients",
  description: "Lists Financeit clients the signed-in user has access to. Admins see all clients; other users see clients they are assigned to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("clients").select("id, name, reporting_period_type, start_day_of_month, created_at").order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-time-entries.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_time_entries_default = defineTool3({
  name: "list_my_time_entries",
  title: "List my time entries",
  description: "Lists the signed-in user's time entries, most recent first. Admins see every user's entries.",
  inputSchema: {
    limit: z.number().int().positive().describe("Maximum number of entries to return (default 50).").optional(),
    client_id: z.string().uuid().describe("Optional client id filter.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, client_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser3(ctx).from("time_entries").select(
      "id, user_id, client_id, activity_description, start_time, end_time, is_extra_hours, created_at"
    ).order("start_time", { ascending: false }).limit(limit ?? 50);
    if (client_id) query = query.eq("client_id", client_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-time-entry.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_time_entry_default = defineTool4({
  name: "create_time_entry",
  title: "Create time entry",
  description: "Creates a new time entry for the signed-in user against one of their clients.",
  inputSchema: {
    client_id: z2.string().uuid().describe("Client id (must be accessible to the user)."),
    activity_description: z2.string().trim().min(1).describe("Description of the activity."),
    start_time: z2.string().describe("Start timestamp in ISO 8601 format."),
    end_time: z2.string().describe("End timestamp in ISO 8601 format."),
    is_extra_hours: z2.boolean().describe("Whether this is extra/overtime hours.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ client_id, activity_description, start_time, end_time, is_extra_hours }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("time_entries").insert({
      user_id: ctx.getUserId(),
      client_id,
      activity_description,
      start_time,
      end_time,
      is_extra_hours: is_extra_hours ?? false
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mgmhhltfdiigsvkirgyz";
var mcp_default = defineMcp({
  name: "financeit-mcp",
  title: "Financeit MCP",
  version: "0.1.0",
  instructions: "Tools for Financeit's authenticated workspace. Use `get_my_profile` to identify the signed-in user, `list_my_clients` to see accessible clients, `list_my_time_entries` to review timesheet entries, and `create_time_entry` to log new work. All operations run as the signed-in user with row-level security enforced.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_clients_default, list_my_time_entries_default, create_time_entry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
